#!/bin/sh
awk '{print gsub("Tmar","")}' Orthogroups.txt > Tmar_family
awk '{print gsub("Tcr1","")}' Orthogroups.txt > Tcr1_family
awk '{print gsub("Tcr2","")}' Orthogroups.txt > Tcr2_family
awk '{print gsub("Tcr5","")}' Orthogroups.txt > Tcr5_family
awk '{print gsub("Tgra","")}' Orthogroups.txt > Tgra_family
awk '{print gsub("Tbrg","")}' Orthogroups.txt > Tbrg_family
awk '{print gsub("Tbr1","")}' Orthogroups.txt > Tbr1_family
awk '{print gsub("Tbru","")}' Orthogroups.txt > Tbru_family
awk '{print gsub("Teva","")}' Orthogroups.txt > Teva_family
awk '{print gsub("Tcon","")}' Orthogroups.txt > Tcon_family
awk '{print gsub("Tviv","")}' Orthogroups.txt > Tviv_family
awk '{print gsub("Pem1","")}' Orthogroups.txt > Pem1_family
awk '{print gsub("Phar","")}' Orthogroups.txt > Phar_family
awk '{print gsub("LBRM2903","")}' Orthogroups.txt > Lbr1_family
awk '{print gsub("Lbr2","")}' Orthogroups.txt > Lbr2_family
awk '{print gsub("Ltar","")}' Orthogroups.txt > Ltar_family
awk '{print gsub("Lmex","")}' Orthogroups.txt > Lmex_family
awk '{print gsub("Lmaj","")}' Orthogroups.txt > Lmaj_family
awk '{print gsub("Linf","")}' Orthogroups.txt > Linf_family
awk '{print gsub("Ldon","")}' Orthogroups.txt > Ldon_family
awk '{print gsub("Cfas","")}' Orthogroups.txt > Cfas_family
awk '{print gsub("Lpyr","")}' Orthogroups.txt > Lpyr_family
awk '{print gsub("Lsey","")}' Orthogroups.txt > Lsey_family
awk '{print gsub("Baya","")}' Orthogroups.txt > Baya_family
awk '{print gsub("Pconf","")}' Orthogroups.txt > Pcon_family
awk '{print gsub("Tbor","")}' Orthogroups.txt > Tbor_family
awk '{print gsub("Bsal","")}' Orthogroups.txt > Bsal_family
awk '{print gsub("Perk","")}' Orthogroups.txt > Perk_family
awk '{print gsub("Ngrub","")}' Orthogroups.txt > Ngrub_family
awk '{print gsub("Ndesig","")}' Orthogroups.txt > Ndesig_family
awk '{print $1}' Orthogroups.txt > OG_numbers
