#!/bin/bash
#option -E undocumented for usage of extended regular expression
cd /home/tomas/Mac_data/m6A_review/proteom_dataset/
#sed -E s/\>\([a-zA-Z]+_[0-9]+\.[0-9]\).*/">Amissi "\\1/ Amissi.fasta >Amissi_renamed.fa
#sed -E s/\>\([a-zA-Z]+_[0-9]+\.[0-9]\).*/">Amissi "\\1/ Amissi.fasta >Amissi_renamed.fa
sed -E s/\>\([a-zA-Z]+_[0-9]+\.[0-9]\).*/">Athali "\\1/ Athali.fasta >Athali_renamed.fa
sed -E s/\>\([a-zA-Z]+_[0-9]+\.[0-9]\).*/">Bbelch "\\1/ Bbelch.fasta >Bbelch_renamed.fa
sed -E s/\>\([a-zA-Z]+_[0-9]+\.[0-9]\).*/">Btauru "\\1/ Btauru.fasta >Btauru_renamed.fa
sed -E s/\>\([a-zA-Z]+_[0-9]+\.[0-9]\).*/">Ccoron "\\1/ Ccoron.fasta >Ccoron_renamed.fa
sed -E s/\>\([a-zA-Z]+_[0-9]+\.[0-9]\).*/">Celega "\\1/ Celega.fasta >Celega_renamed.fa
sed -E s/\>\([a-zA-Z]+_[0-9]+\.[0-9]\).*/">Cmerol "\\1/ Cmerol.fasta >Cmerol_renamed.fa
sed -E s/\>\([a-zA-Z]+_[0-9]+\.[0-9]\).*/">Cowcza "\\1/ Cowcza.fasta >Cowcza_renamed.fa
sed -E s/\>\([a-zA-Z]+_[0-9]+\.[0-9]\).*/">Cpicta "\\1/ Cpicta.fasta >Cpicta_renamed.fa
sed -E s/\>\([a-zA-Z]+_[0-9]+\.[0-9]\).*/">Creinh "\\1/ Creinh.fasta >Creinh_renamed.fa
sed -E s/\>\([a-zA-Z]+_[0-9]+\.[0-9]\).*/">Ddisco "\\1/ Ddisco.fasta >Ddisco_renamed.fa
sed -E s/\>\([a-zA-Z]+_[0-9]+\.[0-9]\).*/">Drerio "\\1/ Drerio.fasta >Drerio_renamed.fa
sed -E s/\>\([a-zA-Z]+_[0-9]+\.[0-9]\).*/">Ehuxle "\\1/ Ehuxle.fasta >Ehuxle_renamed.fa
sed -E s/\>\([a-zA-Z]+_[0-9]+\.[0-9]\).*/">Epalli "\\1/ Epalli.fasta >Epalli_renamed.fa
sed -E s/\>\([a-zA-Z]+_[0-9]+\.[0-9]\).*/">Escher "\\1/ Escher.fasta >Escher_renamed.fa
sed -E s/\>\([a-zA-Z]+_[0-9]+\.[0-9]\).*/">Esilic "\\1/ Esilic.fasta >Esilic_renamed.fa
sed -E s/\>\([a-zA-Z]+_[0-9]+\.[0-9]\).*/">Ggallu "\\1/ Ggallu.fasta >Ggallu_renamed.fa
sed -E s/\>\([a-zA-Z]+_[0-9]+\.[0-9]\).*/">Gintes "\\1/ Gintes.fasta >Gintes_renamed.fa
sed -E s/\>\([a-zA-Z]+_[0-9]+\.[0-9]\).*/">Gjapon "\\1/ Gjapon.fasta >Gjapon_renamed.fa
sed -E s/\>\([a-zA-Z]+_[0-9]+\.[0-9]\).*/">Hsapie "\\1/ Hsapie.fasta >Hsapie_renamed.fa
sed -E s/\>\([a-zA-Z]+_[0-9]+\.[0-9]\).*/">Hvulga "\\1/ Hvulga.fasta >Hvulga_renamed.fa
sed -E s/\>\([a-zA-Z]+_[0-9]+\.[0-9]\).*/">Lchalu "\\1/ Lchalu.fasta >Lchalu_renamed.fa
sed -E s/\>\([a-zA-Z]+_[0-9]+\.[0-9]\).*/">Lmajor "\\1/ Lmajor.fasta >Lmajor_renamed.fa
sed -E s/\>\([a-zA-Z]+_[0-9]+\.[0-9]\).*/">Mbrevi "\\1/ Mbrevi.fasta >Mbrevi_renamed.fa
sed -E s/\>\([a-zA-Z]+_[0-9]+\.[0-9]\).*/">Mmuscu "\\1/ Mmuscu.fasta >Mmuscu_renamed.fa
sed -E s/\>\([a-zA-Z]+_[0-9]+\.[0-9]\).*/">Ngrube "\\1/ Ngrube.fasta >Ngrube_renamed.fa
sed -E s/\>\([a-zA-Z]+_[0-9]+\.[0-9]\).*/">Nparke "\\1/ Nparke.fasta >Nparke_renamed.fa
sed -E s/\>\([a-zA-Z]+_[0-9]+\.[0-9]\).*/">Nvecte "\\1/ Nvecte.fasta >Nvecte_renamed.fa
sed -E s/\>\([a-zA-Z]+_[0-9]+\.[0-9]\).*/">Ohanna "\\1/ Ohanna.fasta >Ohanna_renamed.fa
sed -E s/\>\([a-zA-Z]+_[0-9]+\.[0-9]\).*/">Osativ "\\1/ Osativ.fasta >Osativ_renamed.fa
sed -E s/\>\([a-zA-Z]+_[0-9]+\.[0-9]\).*/">Rfilos "\\1/ Rfilos.fasta >Rfilos_renamed.fa
sed -E s/\>\([a-zA-Z]+_[0-9]+\.[0-9]\).*/">Rtypus "\\1/ Rtypus.fasta >Rtypus_renamed.fa
sed -E s/\>\([a-zA-Z]+_[0-9]+\.[0-9]\).*/">Scerev "\\1/ Scerev.fasta >Scerev_renamed.fa
sed -E s/\>\([a-zA-Z]+_[0-9]+\.[0-9]\).*/">Smanso "\\1/ Smanso.fasta >Smanso_renamed.fa
sed -E s/\>\([a-zA-Z]+_[0-9]+\.[0-9]\).*/">Spombe "\\1/ Spombe.fasta >Spombe_renamed.fa
sed -E s/\>\([a-zA-Z]+_[0-9]+\.[0-9]\).*/">Tadhae "\\1/ Tadhae.fasta >Tadhae_renamed.fa
sed -E s/\>\([a-zA-Z]+_[0-9]+\.[0-9]\).*/">Tbruce "\\1/ Tbruce.fasta >Tbruce_renamed.fa
sed -E s/\>\([a-zA-Z]+_[0-9]+\.[0-9]\).*/">Tgondi "\\1/ Tgondi.fasta >Tgondi_renamed.fa
sed -E s/\>\([a-zA-Z]+_[0-9]+\.[0-9]\).*/">Tpseud "\\1/ Tpseud.fasta >Tpseud_renamed.fa
sed -E s/\>\([a-zA-Z]+_[0-9]+\.[0-9]\).*/">Ttherm "\\1/ Ttherm.fasta >Ttherm_renamed.fa
sed -E s/\>\([a-zA-Z]+_[0-9]+\.[0-9]\).*/">Tvagin "\\1/ Tvagin.fasta >Tvagin_renamed.fa
sed -E s/\>\([a-zA-Z]+_[0-9]+\.[0-9]\).*/">Vcarte "\\1/ Vcarte.fasta >Vcarte_renamed.fa
sed -E s/\>\([a-zA-Z]+_[0-9]+\.[0-9]\).*/">Xfasti "\\1/ Xfasti.fasta >Xfasti_renamed.fa
sed -E s/\>\([a-zA-Z]+_[0-9]+\.[0-9]\).*/">Xlaevi "\\1/ Xlaevi.fasta >Xlaevi_renamed.fa
sed -E s/\>\([a-zA-Z]+_[0-9]+\.[0-9]\).*/">Dmelan "\\1/ Dmelan.fasta >Dmelan_renamed.fa
