#!/usr/bin/python
nonspecific_functions = [
       'dynein', 'kinesin', 'tubulin', 'actin', 'myosin', 'formin',
       'clathrin', 'centrin',
       'cytosolic coat',
       'paraflagellar rod component; putative',
       'williams-beuren',
       'transposon', 'repeat',
       'mterf',
       'small gtp-binding protein rab',
       'ribosome-associated gtpase ',
       'ras-like small gtpase',
       'kinase',
       'phosphatase',
       'adenylate cyclase',
       'adp-ribosylation',
       'macro domain',
       'sirtuin',
       'calmodulin',
       'angel',
       'cyclophilin',
       'insulin-recepror',
       'mrp', 'abc', 'transloc', 'permease', 'atp-binding cassette', 'porter',
       'solute carrier',
       'regulator of microtubule dynamics',
       'required for meiotic nuclear division 1 homolog',
       'gtpase-activating protein',
       'vesicle membrane protein',
       'universal minicircle sequence binding protein',
       'lactamase',
       'pump',
       'endosomal integral membrane protein; putative',
       'stomatin',
       'chaperon', 'chaperonin',
       'histon', 'dnaj', 'nucleosome remodeling',
       'component of the condensin complex',
       'peptidas', 'protease',
       'proteasome',
       'ubiquitin',
       'dead', 'deah',
       'rna binding',
       'poly(a)',
       'helicase',
       'ligase',
       'polymerase',
       'nuclease',
       'topoisomerase',
       'photolyase',
       'muts', 'mutl',
       'mrb1-',
       'kiaa0141'
       ]
