#!/usr/bin/python
from Bio.SeqRecord import SeqRecord
from Bio import SeqIO
from Bio.Seq import Seq

ter = 'MAMFTTTAKVIQPKIRGFICTTTHPIGCEKRVQEELAYARAHPPTSPGPKRVLVLGCSTGYGLSTRITAATFYQAATLGVFLAGPPTKGRPAAAGWYNTVAFEKAALEAGLYARSLNGDAFDSTTKARTVEAIKRDLGTVDLVVYSIAAPKRTDPATGVLHKACLKPLGATYTNRTVNTDKAEVTDVSIEPASPEEIADTVKVMGGEDWELWIQALSEAGVLAEGAKTVAYSYIGPEMTWPVYWSGTIGEAKKDVEKAAKRITQQYGCPAYPVVAKALVTQASSAIPVVPLYICLLYRVMKEKGTHEGCLEQMVRLLTTKLYPENGAPLVDEQRVRVDDWEMAEDVQQAVKDLWSQVNTANLKDISDFAGYQTEFLRLFGFGIDGVDYDQPVDVEADLPSAAQQ'
result_seqs = []
result_seqs.append(SeqRecord(seq=Seq(ter), id='TER_egracilis', description=''))

out_file = '/home/anna/Dropbox/phd/mitoproteomes/proteomes/euglena/ter_egracilis.fasta'
SeqIO.write(result_seqs, out_file, "fasta")